# Generated by Django 5.1.7 on 2025-03-16 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diabetes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("date_sent", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("daily_notification", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
