# Generated by Django 5.1.7 on 2025-03-17 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diabetes", "0002_medicationrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articles",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="video_url",
        ),
        migrations.DeleteModel(
            name="ArticleRating",
        ),
    ]
